### ISSUE TITLE
[Question] Script to overwrite and update

### ISSUE THREAD

**Issue by plissken1138** [Crozzers/ffmpeg-installer#1]
Can you please post a version of the script that overwrites the directory, without adding to PATH, for purpose of updating?

I have next to zero knowledge of python and trying to modify the script led me nowhere.

TIA

**Comment by Crozzers** [comment]
I added an `--overwrite` flag to the command line which will overwrite an existing install.
As for adding to PATH, the script will prompt you before adding anything to PATH, which you can decline if you wish.

That being said, I would also highly recommend checking out [Chocolatey](https://chocolatey.org/why-chocolatey), which is a package manager for Windows that has ffmpeg installers available and will probably handle updates and multiple ffmpeg versions much better than this one-off script I wrote.

This script is good if you just want to install ffmpeg, Chocolatey is good if you want to install multiple programs and keep them up to date

**Comment by plissken1138** [comment]
Thanks for the fast response! This will work for my use. I'll check out Chocolatey.
