### ISSUE TITLE
Win Path

### ISSUE THREAD

**Issue by Arrowar** [Crozzers/ffmpeg-installer#4]
From 10 path after install ffmpeg there are about 130 new path. 
There is same problem with os.get("path") that find too much path.

**Comment by Crozzers** [comment]
Do you mean the script is adding too many things to the PATH? Tested this and wasn't able to reproduce. Can you share any more details about the issue?

**Comment by Arrowar** [comment]
> Do you mean the script is adding too many things to the PATH? Tested this and wasn't able to reproduce. Can you share any more details about the issue?

Yes but i solve, problem with my configuration of python.
